myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

myshop/payment/urls.py
from django.conf.urls import url
from . import views

app_name = 'payment'

urlpatterns = [
    url(r'^process/$', views.payment_process, name='process'),
    url(r'^done/$', views.payment_done, name='done'),
    url(r'^canceled/$', views.payment_canceled, name='canceled'),
]

myshop/payment/models.py
from django.db import models

# Create your models here.

myshop/payment/views.py
from decimal import Context, Decimal, getcontext
from django.conf import settings
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from paypal.standard.forms import PayPalPaymentsForm
from orders.models import Order
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def payment_done(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    order.paid = True
    order.status = "Pedido"
    order.save()
    return render(request,'payment/done.html', {'order':order})


@csrf_exempt
def payment_canceled(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    order.status = "Pedido"
    order.save()
    return render(request,'payment/canceled.html')


def payment_process(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    order.status = 'Pedido'
    order.save()
    host = request.get_host()
    if request.method == 'POST' and 'cash_payment' in request.POST:
        return render(request, 'orders/order/created.html', {'order': order})

    paypal_dict ={
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': order.get_total_cost(),
        #'amount': '%.2f'% decimal (order.get_total_cost()).quantize(decimal('.01')),
        'item_name': 'Order {}'.format(order.id),
        'invoice': str(order.id),
        'currency_code': 'MXN',
        'notify_url': 'http://{}{}'.format(host,reverse('paypal-ipn')),
        'return_url': 'http://{}{}'.format(host,reverse('payment:done')),
        'cancel_return': 'http://{}{}'.format(host,reverse('payment:canceled')),
    }

    form = PayPalPaymentsForm(initial=paypal_dict)
    return render(request,'payment/process.html',{'order':order,'form':form})

myshop/payment/templates/payment/canceled.html
{% extends "shop/base.html" %}

{% block content %}
    <h1>El pago ha sido cancelado</h1>
    <p>Ocurrió un error con tu pago</p>
    <a href="{% url 'payment:process' %}">Regresar a las formas de pago</a>
{% endblock %}

myshop/payment/templates/payment/done.html
{% extends "shop/base.html" %}

{% block content %}
    <h1>El pago fue realizado de manera exitosa</h1>
    <p>El pago ha sido recibido</p>
    <p>Su orden se ha completado. El número de la orden es <strong>{{ order.id }}</strong>.</p>
{% endblock %}

myshop/payment/templates/payment/process.html
{% extends "shop/base.html" %}
{% block title %} Pago usando PayPal {% endblock %}
{% block content %}
    <h1>Selecciona tu forma de pago</h1>
    {{form.render}}
    <form action="." method="post" class="cash-form">
        <p><input type="submit" value="Pago en efectivo" name="cash_payment"></p>
        {% csrf_token %}
    </form>
{% endblock %}}